name = "kiddyvibe-com"
main = "src/server/index.ts"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "forme-production"
database_id = "3c855370-eb43-4496-b3ee-b39a689b012a"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "forme-product-media"

[vars]
META_API_VERSION = "v21.0"
